/**
 * Regenerates `src/lib/universe/sp500.ts` from the public constituents dataset.
 *
 * Run by hand and commit the result — the app must not depend on a third party
 * being up at build time, and an index that changes a handful of times a year
 * does not need to be fetched on every deploy.
 *
 *   npx tsx scripts/build-universe.ts
 */
import { writeFile } from "node:fs/promises";

const SOURCE =
  "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv";

/** Splits one CSV line, honouring the quoted commas in "City, State". */
function splitCsvLine(line: string): string[] {
  const fields: string[] = [];
  let current = "";
  let quoted = false;

  for (const character of line) {
    if (character === '"') quoted = !quoted;
    else if (character === "," && !quoted) {
      fields.push(current);
      current = "";
    } else current += character;
  }
  fields.push(current);
  return fields;
}

/** Yahoo writes class shares with a dash where the index uses a dot. */
const toYahoo = (symbol: string) => symbol.replace(/\./g, "-");

async function main() {
  const response = await fetch(SOURCE);
  if (!response.ok) throw new Error(`Source returned ${response.status}`);

  const rows = (await response.text())
    .trim()
    .split("\n")
    .slice(1)
    .map(splitCsvLine)
    .map(([symbol, name, sector]) => ({
      symbol: toYahoo(symbol.trim()),
      name: name.trim(),
      sector: sector.trim(),
    }))
    .filter((row) => row.symbol && row.name && row.sector)
    .sort((a, b) => a.symbol.localeCompare(b.symbol));

  const sectors = [...new Set(rows.map((row) => row.sector))].sort();

  const file = `// Generated by scripts/build-universe.ts — do not edit by hand.
// Source: ${SOURCE}
// Regenerated ${new Date().toISOString().slice(0, 10)}.

export interface UniverseEntry {
  readonly symbol: string;
  readonly name: string;
  readonly sector: string;
}

export const SP500_SECTORS = [
${sectors.map((sector) => `  ${JSON.stringify(sector)},`).join("\n")}
] as const;

export type Sector = (typeof SP500_SECTORS)[number];

export const SP500: readonly UniverseEntry[] = [
${rows
  .map(
    (row) =>
      `  { symbol: ${JSON.stringify(row.symbol)}, name: ${JSON.stringify(
        row.name,
      )}, sector: ${JSON.stringify(row.sector)} },`,
  )
  .join("\n")}
];
`;

  await writeFile(new URL("../src/lib/universe/sp500.ts", import.meta.url), file);
  console.log(`Wrote ${rows.length} constituents across ${sectors.length} sectors.`);
}

void main();
